# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ADC_RX_Test/ADC_RX_Test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_RX_Test || ORIG_REF_NAME==ADC_RX_Test} -quiet] -quiet

# IP: bd/ADC_RX_Test/ip/ADC_RX_Test_spi_0_0/ADC_RX_Test_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_RX_Test_spi_0_0 || ORIG_REF_NAME==ADC_RX_Test_spi_0_0} -quiet] -quiet

# IP: bd/ADC_RX_Test/ip/ADC_RX_Test_uart_adc_0_0/ADC_RX_Test_uart_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_RX_Test_uart_adc_0_0 || ORIG_REF_NAME==ADC_RX_Test_uart_adc_0_0} -quiet] -quiet

# IP: bd/ADC_RX_Test/ip/ADC_RX_Test_ila_0_0/ADC_RX_Test_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ADC_RX_Test_ila_0_0 || ORIG_REF_NAME==ADC_RX_Test_ila_0_0} -quiet] -quiet

# XDC: bd/ADC_RX_Test/ADC_RX_Test_ooc.xdc
