# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zynq7020.xdc

# Block Designs: bd/Zynq_Interconnect/Zynq_Interconnect.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect || ORIG_REF_NAME==Zynq_Interconnect} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_processing_system7_0_0/Zynq_Interconnect_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_processing_system7_0_0 || ORIG_REF_NAME==Zynq_Interconnect_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_axi_gpio_0_0/Zynq_Interconnect_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_axi_gpio_0_0 || ORIG_REF_NAME==Zynq_Interconnect_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_axi_gpio_0_1/Zynq_Interconnect_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_axi_gpio_0_1 || ORIG_REF_NAME==Zynq_Interconnect_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_xbar_0/Zynq_Interconnect_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_xbar_0 || ORIG_REF_NAME==Zynq_Interconnect_xbar_0} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_ps7_0_axi_periph_0/Zynq_Interconnect_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_Interconnect_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_rst_ps7_0_50M_0/Zynq_Interconnect_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_rst_ps7_0_50M_0 || ORIG_REF_NAME==Zynq_Interconnect_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_util_vector_logic_0_0/Zynq_Interconnect_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_util_vector_logic_0_0 || ORIG_REF_NAME==Zynq_Interconnect_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_auto_pc_0/Zynq_Interconnect_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_auto_pc_0 || ORIG_REF_NAME==Zynq_Interconnect_auto_pc_0} -quiet] -quiet

# IP: bd/Zynq_Interconnect/ip/Zynq_Interconnect_auto_pc_1/Zynq_Interconnect_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_Interconnect_auto_pc_1 || ORIG_REF_NAME==Zynq_Interconnect_auto_pc_1} -quiet] -quiet

# XDC: bd/Zynq_Interconnect/Zynq_Interconnect_ooc.xdc
