# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Extra_Projects/basys3uart/basysuart/basysuart.srcs/sources_1/ip/memory_data/memory_data.xci
# IP: The module: 'memory_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Extra_Projects/basys3uart/basysuart/basysuart.srcs/sources_1/ip/memory_data/memory_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Extra_Projects/basys3uart/basysuart/basysuart.srcs/sources_1/ip/memory_data/memory_data.xci
# IP: The module: 'memory_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Extra_Projects/basys3uart/basysuart/basysuart.srcs/sources_1/ip/memory_data/memory_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
