# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Extra_Projects/Zynq/Zynq_Basic_Task/Zynq_Basic_Task.srcs/sources_1/bd/Zynq_Interconnect/ip/Zynq_Interconnect_auto_pc_0/Zynq_Interconnect_auto_pc_0.xci
# IP: The module: 'Zynq_Interconnect_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Extra_Projects/Zynq/Zynq_Basic_Task/Zynq_Basic_Task.srcs/sources_1/bd/Zynq_Interconnect/ip/Zynq_Interconnect_auto_pc_0/Zynq_Interconnect_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Interconnect_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Extra_Projects/Zynq/Zynq_Basic_Task/Zynq_Basic_Task.srcs/sources_1/bd/Zynq_Interconnect/ip/Zynq_Interconnect_auto_pc_0/Zynq_Interconnect_auto_pc_0.xci
# IP: The module: 'Zynq_Interconnect_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Extra_Projects/Zynq/Zynq_Basic_Task/Zynq_Basic_Task.srcs/sources_1/bd/Zynq_Interconnect/ip/Zynq_Interconnect_auto_pc_0/Zynq_Interconnect_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_Interconnect_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
