# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Basys3_Master.xdc

# Block Designs: bd/Lab_ADC/Lab_ADC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC || ORIG_REF_NAME==Lab_ADC} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_ADC_FSM_0_0/Lab_ADC_ADC_FSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_ADC_FSM_0_0 || ORIG_REF_NAME==Lab_ADC_ADC_FSM_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_CLK_DIVIDER_0_0/Lab_ADC_CLK_DIVIDER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_CLK_DIVIDER_0_0 || ORIG_REF_NAME==Lab_ADC_CLK_DIVIDER_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_Edge_Detector_0_0/Lab_ADC_Edge_Detector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_Edge_Detector_0_0 || ORIG_REF_NAME==Lab_ADC_Edge_Detector_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_Edge_Detector_1_0/Lab_ADC_Edge_Detector_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_Edge_Detector_1_0 || ORIG_REF_NAME==Lab_ADC_Edge_Detector_1_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_PreEmphasisFilter_0_0/Lab_ADC_PreEmphasisFilter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_PreEmphasisFilter_0_0 || ORIG_REF_NAME==Lab_ADC_PreEmphasisFilter_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_RAM_Controller_0_0/Lab_ADC_RAM_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_RAM_Controller_0_0 || ORIG_REF_NAME==Lab_ADC_RAM_Controller_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_blk_mem_gen_0_0/Lab_ADC_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_blk_mem_gen_0_0 || ORIG_REF_NAME==Lab_ADC_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_threshold_0_0/Lab_ADC_threshold_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_threshold_0_0 || ORIG_REF_NAME==Lab_ADC_threshold_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_blk_mem_gen_1_0/Lab_ADC_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_blk_mem_gen_1_0 || ORIG_REF_NAME==Lab_ADC_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_mult_gen_0_0/Lab_ADC_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_mult_gen_0_0 || ORIG_REF_NAME==Lab_ADC_mult_gen_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_Lab_Window_Controller_0_0/Lab_ADC_Lab_Window_Controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_Lab_Window_Controller_0_0 || ORIG_REF_NAME==Lab_ADC_Lab_Window_Controller_0_0} -quiet] -quiet

# IP: bd/Lab_ADC/ip/Lab_ADC_ila_0_0/Lab_ADC_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_ADC_ila_0_0 || ORIG_REF_NAME==Lab_ADC_ila_0_0} -quiet] -quiet

# XDC: bd/Lab_ADC/Lab_ADC_ooc.xdc
