webtalk_init -webtalk_dir D:/Extra_Projects/basys3uart/basysuart/basysuart.sim/sim_1/behav/xsim/xsim.dir/tb_top_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct 19 23:05:38 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "28f71be3-b0c4-45f8-a474-bd06d41b1090" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "159b730777584a4fa5517ecb163a24a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "72" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15108_KB" -context "xsim\\usage"
webtalk_transmit -clientid 934372831 -regid "" -xml D:/Extra_Projects/basys3uart/basysuart/basysuart.sim/sim_1/behav/xsim/xsim.dir/tb_top_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Extra_Projects/basys3uart/basysuart/basysuart.sim/sim_1/behav/xsim/xsim.dir/tb_top_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Extra_Projects/basys3uart/basysuart/basysuart.sim/sim_1/behav/xsim/xsim.dir/tb_top_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
