# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_mult_gen_0_0/AudioProcessing_mult_gen_0_0.xci
# IP: The module: 'AudioProcessing_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_mult_gen_0_0/AudioProcessing_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioProcessing_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_mult_gen_0_0/AudioProcessing_mult_gen_0_0.xci
# IP: The module: 'AudioProcessing_mult_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_mult_gen_0_0/AudioProcessing_mult_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioProcessing_mult_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
