# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_fir_compiler_1_0/AudioProcessing_fir_compiler_1_0.xci
# IP: The module: 'AudioProcessing_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioProcessing_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_fir_compiler_1_0/AudioProcessing_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioProcessing_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_fir_compiler_1_0/AudioProcessing_fir_compiler_1_0.xci
# IP: The module: 'AudioProcessing_fir_compiler_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioProcessing_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/GitHub Repos/MISC_Embedded_Projects/FreeLancing Projects Files/AudioProcessing/Vivado_Files/AudioProcessing/AudioProcessing.srcs/sources_1/bd/AudioProcessing/ip/AudioProcessing_fir_compiler_1_0/AudioProcessing_fir_compiler_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioProcessing_fir_compiler_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
